[package]
name = "wukong-memory"
edition.workspace = true
version.workspace = true

[dependencies]
tokio = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dependencies.fastembed]
version = "4"
optional = true

[features]
embed = ["dep:fastembed"]

[dev-dependencies]
tempfile = { workspace = true }
